October23 integration
checkmarx-ltd/Cx-Client-Common pull request #229
Opened 2023-10-30 12:06 UTC by Khant1000

By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ltd/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

AvoidDuplicateProjectScans parameter :
Sample command:
runCxConsole.cmd Scan -v -ProjectName "CxServer/dupProjTest2" -TrustedCertificates -CxServer https://sast94.cxquality.com/ -cxuser admin@cx -cxpassword Cx123456! -LocationType folder -LocationPath "C:\CLIPlugin\GitRepo\JavaVulnerableLabE" -preset "Checkmarx Default" -AvoidDuplicateProjectScans
Expected behavior : when this parameter is used and a sast scan is run simultaneously on two cmd, using same project name, one of the scans should happen successfully, on the other prompt it should throw the error :
CLI process terminated, error: com.cx.restclient.exception.CxClientException: Avoid duplicate project scans in queue.
avoidDuplicateProjectScans : true in cx.config
Sample command:
runCxConsole.cmd Scan -ProjectName "CxServer/SP/Checkmarx/ConfigAsCodeDupScan1.5" -CxServer https://sast94.cxquality.com/ -cxuser admin@cx -cxpassword Cx123456! -LocationType folder -LocationPath "C:\CLIPlugin\GitRepo\JavaVulnerableLabE" -preset "Checkmarx Default" -configascode
Expected Behivior : Similar to 1.
when the flag is set to false, both the scans should happen successfully.

On running a SCA scan on CLI Code, Initially there were 5 high level vulnerabilities and 3 medium level vulnerabilities. The rest of the vulnerabilities have been taken care of by updating the dependencies to the recommended versions. But,
There still exists one medium level vulnerability, for a direct dependency : [org.bouncycastle:bcprov-jdk15on @ 1.70](https://sca.checkmarx.net/#/projects/e331a09f-1e0f-48c7-871d-13f104d00b87/reports/886ebe20-d7dd-4b7a-bf97-ba5f31e6a77d/packages/Maven-org.bouncycastle%3Abcprov-jdk15on-1.70/packageDetailsGql) ,
which is because the latest version of the dependency itself has vulnerabilities.
CxSCA

[PLUG-1395](https://checkmarx.atlassian.net/browse/PLUG-1395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) [CLI] Salesforce | 00180205 | In 9.6 ScanWithSettings V5 is not accepting a zip file if it's a GIT, SVN, TFS or a Perforce project - Jira (atlassian.net) . should be able to perform scan with 9.6 server without hotfix.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change.

### References

> Include supporting link to GitHub Issue/PR number

### Testing

> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentaiton is a Wiki Update, please indicate desired changes within PR MD Comment*
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used

2023-10-30 12:48 UTC, umeshwaghode requested changes
The work related to version handling requires some more work.

2023-10-30 12:48 UTC, umeshwaghode commented on src/main/java/com/cx/restclient/CxSASTClient.java
> +    	               if ("SAST_RETENTION_RATE".equals(apiName) && config.isEnableDataRetention()) {
Use equalIgnoreCase at all places and use consistent naming convention for 'apiName'. In one case it is all upper case with underscore while at other place it is camel casing.

2023-10-30 12:48 UTC, umeshwaghode commented on src/main/java/com/cx/restclient/CxSASTClient.java
> +    public String getContentTypeAndApiVersion(CxScanConfig config, String apiName) {
This class does call out for some comments.

2023-10-30 12:48 UTC, umeshwaghode commented on src/main/java/com/cx/restclient/CxSASTClient.java
> +    	                   } else if (config.getPostScanActionId() != null && config.getPostScanActionId() == 1) {
This condition is not accurate. Why ==1?

2023-10-30 12:48 UTC, umeshwaghode commented on src/main/java/com/cx/restclient/httpClient/CxHttpClient.java
> +		if ("sast/scanWithSettings".equals(relPath)) {
This is no correct,   CxHTTPClient is a generic HTTPClient.  We cannot have API endpoints in the logic here. Instead, logic can be on the basis of Content-Type

2023-10-30 12:48 UTC, umeshwaghode commented on src/main/java/com/cx/restclient/httpClient/CxHttpClient.java
> +    private <T> T requestForMultipartFile(HttpRequestBase httpMethod, String contentType, HttpEntity entity, Class<T> responseType, int expectStatus, String failedMsg, boolean isCollection, boolean r
We do not need duplicate method. This need to be fixed.

2023-11-02 15:19 UTC, umeshwaghode requested changes

2023-11-02 15:19 UTC, umeshwaghode commented on src/main/java/com/cx/restclient/CxSASTClient.java
> +            String apiVersion = getContentTypeAndApiVersion(config, SCAN_WITH_SETTINGS_URL);
The function should have been called for the API SAST_ZIP_ATTACHMENTS instead of SCAN_WITH_SETTINGS_URL

2023-11-02 15:19 UTC, umeshwaghode commented on src/main/java/com/cx/restclient/CxSASTClient.java
> +        return httpClient.postRequest(String.format(SAST_CREATE_REMOTE_SOURCE_SCAN, projectId, sourceType, isSSH ? "ssh" : ""), isSSH ? null : CONTENT_TYPE_APPLICATION_JSON_V1, apiVersion,
The function should have been called for the API SAST_CREATE_REMOTE_SOURCE_SCAN,instead of SCAN_WITH_SETTINGS_URL

2023-11-02 19:22 UTC, PravinGadankush approved these changes

2023-11-03 10:54 UTC, umeshwaghode submitted a review, later dismissed

2023-11-03 11:10 UTC, umeshwaghode approved these changes

2023-11-03 14:11 UTC, PravinGadankush approved these changes

2023-11-03 14:11 UTC, umeshwaghode approved these changes

2023-11-03 14:12 UTC, merged